import Head from "next/head";
import Image from "next/image";
import {Inter} from "@next/font/google";
import TopNav from "@/components/TopNav";
import Heroes from "@/components/Heroes";
import SearchBar from "@/components/SearchBar";
import ArticlesContainer from "@/components/ArticlesContainer";
import {data} from "@/data/article";

const inter = Inter({subsets: ["latin"]});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <TopNav />

        <Heroes />
        <ArticlesContainer articles={data}>
          <div className='mx-20 mt-3 mb-3 p-5'>
            <SearchBar />
          </div>
        </ArticlesContainer>
      </main>
    </>
  );
}
